databaseChangeLog:
  - changeSet:
      id: "v1.005.1"
      author: Alexander Sadovnikov
      comment: "Add table application_instance"
      changes:
        - createTable:
            tableName: application_instance
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    nullable: false
                    primaryKey: true
                  defaultValueComputed: uuid_generate_v4()
              - column:
                  name: application_id
                  type: uuid
                  constraints:
                    foreignKeyName: fk_application
                    references: application(id)
                    nullable: false
              - column:
                  name: public_key
                  type: varchar
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: fingerprint
                  type: varchar
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: last_active_at
                  type: timestamp
              - column:
                  name: device_type
                  type: varchar
                  constraints:
                    nullable: false
                  defaultValue: empty
              - column:
                  name: blocked
                  type: boolean
                  constraints:
                    nullable: false
                  defaultValueBoolean: false